# hostPath 유형을 사용하는 영구 볼륨
# 단일 노드 테스트 환경에서만 작동한다.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  # 클러스터에서 실행되는 다양한 pod에서 사용하는 capacity를 제어하기 위해서
  # 전체 사용 가능한 용량 지정
  capacity:
    - storage: 1Gi
  volumeMode: Filesystem # 가상 머신 내부의 파일 시스템에 폴더가 있기 때문에 # Filesystem, Block
  # 여러 액세스 모드를 허용하는 키를 추가하여 설정한다.
  accessMode:
    - ReadWriteOnce # 단일 노드에 의해 읽기/쓰기 볼륨으로 마운트 될 수 있음을 의미 # 여러 pod에 의해 수행되지만 동일한 노드에 있어야 한다.
    # - ReadOnlyMany # 여러 노드에서 읽기 요청할 수 있음을 의미
    # - ReadWriteMany # 여러 노드에서 읽기/쓰기 요청할 수 있음을 의미
  hostPath:
    path: /data
    type: DirectoryOrCreate